### ISSUE TITLE
Regarding PS

### ISSUE THREAD

**Issue by KrisKnez** [YJBeetle/ccpatch#2]
When patching PS I am not able to make a new file and the home screen does not work. Is this normal behavior?

**Comment by YJBeetle** [comment]
几个月前我也发现了这个问题，并且已经修复，但是带来了一个副作用，现在Ps和Ai的使用必须登陆adobe账户，但是至少在目前的MacOS最新版它可以使用。

**Comment by YJBeetle** [comment]
Translate：I also discovered this problem a few months ago and it has been fixed, but it has brought a side effect. Now Ps and Ai must be logged in to the adobe account, but it can be used at least in the latest version of MacOS.
